#![feature(trace_macros)]

use std::default;

use binrw::binrw;
use tc_save_parser_macros::kind_mapper;

#[kind_mapper]
#[binrw]
#[br(little,repr=u16)]
#[bw(little,repr=u16)]
#[derive(Debug, Clone, Copy, PartialEq, Default)]
#[repr(u16)]
pub enum Kind {
    #[default]
    None = 0,
    Off = 1,
    On = 2,
    NotBit = 3,
    AndBit = 4,
    And3Bit = 5,
    NandBit = 6,
    OrBit = 7,
    Or3Bit = 8,
    NorBit = 9,
    XorBit = 10,
    XnorBit = 11,
    SwitchBit = 12,
    DelayLineBit = 13,
    RegisterBit = 14,
    FullAdder = 15,
    MakerBit8 = 16,
    SplitterBit8 = 17,
    NotWord = 18,
    OrWord = 19,
    AndWord = 20,
    NandWord = 21,
    NorWord = 22,
    XorWord = 23,
    XnorWord = 24,
    SwitchWord = 25,
    Equal = 26,
    LessU = 27,
    LessS = 28,
    Neg = 29,
    Add = 30,
    Mul = 31,
    Div = 32,
    Lsl = 33,
    Lsr = 34,
    Rol = 35,
    Ror = 36,
    Asr = 37,
    Counter = 38,
    RegisterWord = 39,
    ImmRegisterWord = 40,
    ImmDelayLineBit = 41,
    Mux = 42,
    Decoder1 = 43,
    Decoder2 = 44,
    Decoder3 = 45,
    Constant = 46,
    SplitterWord2 = 47,
    MakerWord2 = 48,
    FrontPanel = 49,
    Assembler = 50,
    Ssd = 51,
    Ram = 52,
    RamLatency = 53,
    RamFast = 54,
    DelayLineWord = 55,
    RamDualLoad = 56,
    FileLoader = 57,
    CcLevelOutput = 58,
    LevelGate = 59,
    LevelInput1 = 60,
    LevelInputWord = 61,
    LevelInputSwitched = 62,
    LevelInput2Pin = 63,
    LevelInput3Pin = 64,
    LevelInput4Pin = 65,
    LevelInputCustom = 66,
    LevelInputArch = 67,
    LevelOutput1 = 68,
    LevelOutputWord = 69,
    LevelOutputSwitched = 70,
    LevelOutput1Sum = 71,
    LevelOutput1Car = 72,
    LevelOutput2Pin = 73,
    LevelOutput3Pin = 74,
    LevelOutput4Pin = 75,
    LevelOutputArch = 76,
    LevelOutputCounter = 77,
    Custom = 78,
    CcInput = 79,
    CcInputBuffer = 80,
    CcOutput = 81,
    ProbeMemoryBit = 82,
    ProbeMemoryWord = 83,
    ProbeWireBit = 84,
    ProbeWireWord = 85,
    ConfigDelay = 86,
    Halt = 87,
    Console = 88,
    SegmentDisplay = 89,
    StaticValue = 90,
    PixelScreen = 91,
    Time = 92,
    Keyboard = 93,
    StaticEval = 94,
    VerilogInput = 95,
    VerilogOutput = 96,
    MakerWord4 = 97,
    MakerWord8 = 98,
    SplitterWord4 = 99,
    SplitterWord8 = 100,
    StaticIndexer = 101,
    ImmProbeMemoryBit = 102,
    ImmDelayLineWord = 103,
    Inc = 104,
    CcLevelInputCustom = 105,
    CcLevelInput = 106,
    ImmRegisterBit = 107,
    Mod = 108,
    SplitterBit2 = 109,
    SplitterBit4 = 110,
    MakerBit2 = 111,
    MakerBit4 = 112,
    ImmProbeMemoryWord = 113,
    Concatenator2 = 114,
    Concatenator4 = 115,
    Concatenator8 = 116,
    StaticIndexerConfig = 117,
    Rom = 118,
}

impl Kind {
    pub fn is_memory(&self) -> bool {
        match self {
            // Kind::MemoryBit => true,
            _ => false,
        }
    }
    pub fn is_custom(&self) -> bool {
        match self {
            Kind::Custom => true,
            _ => false,
        }
    }
    pub fn has_linked_components(&self) -> bool {
        match self {
            Kind::Console => true,
            Kind::RamDualLoad => true,
            Kind::RamLatency => true,
            Kind::RamFast => true,
            Kind::Ram => true,
            Kind::Rom => true,
            Kind::ProbeMemoryBit => true,
            Kind::ProbeMemoryWord => true,
            _ => false,
        }
    }
}
